# Generated by Django 5.2.8 on 2026-02-27 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_acceptorrequest_hospital_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptorrequest',
            name='compatibility_requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='acceptorrequest',
            name='medical_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='hla_type',
            field=models.CharField(blank=True, help_text='Encrypted HLA types', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='is_smoker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('NONE', 'Not Submitted'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NONE', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('KYC_UPDATE', 'KYC Status Change'), ('ROLE_CHANGE', 'User Role Modified'), ('INVENTORY_UPDATE', 'Blood Inventory Change'), ('REQUEST_FLAGGED', 'Fake Request Detected'), ('SENSITIVE_DATA_ACCESS', 'Sensitive Data Accessed')], max_length=50)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
