# Generated by Django 5.2.8 on 2026-02-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_acceptorrequest_compatibility_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='average_response_speed',
            field=models.FloatField(default=0.0, help_text='Average hours to respond to alerts'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='total_donations_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='hospitals/licenses/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
