# Generated by Django 5.2.8 on 2026-02-27 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_donorprofile_average_response_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='linked_request',
            field=models.ForeignKey(blank=True, help_text='The patient request this appointment is fulfilling.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='api.acceptorrequest'),
        ),
    ]
